# Generated by Django 3.0.7 on 2020-12-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=250)),
                ('item_quantity', models.CharField(max_length=250)),
                ('item_status', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
            ],
        ),
    ]
