# Generated by Django 3.0.7 on 2020-12-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20201227_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
